---
title: "Estatística Inferencial e Distribuição Normal"
subtitle: "Fundamentos da Inferência Estatística<br>Análise de Dados Ambientais"
author: "Luiz Diego Vidal Santos"
institute: "Universidade Estadual de Feira de Santana (UEFS)"
format:
  revealjs:
    logo: ../../../assets/logo-uefs.webp
    footer: "UEFS | Análise de Dados Ambientais | Estatística Inferencial e Distribuição Normal"
    slide-number: true
    theme: [simple, ../../../assets/uefs.scss]
    controls: true
    width: 1280
    height: 720
    css: ../../../assets/custom.css
    transition: slide
    background-transition: fade
    preview-links: auto
execute:
  echo: false
---

## {.smaller-text}

ESTATÍSTICA INFERENCIAL


---

## ESTATÍSTICA INFERENCIAL {.smaller-text}

**Definição**:

Inferência estatística refere-se aos resultados derivados da análise estatística dos dados coletados.

Ou seja, a inferência estatística advém de uma relação entre a teoria estatística e os dados reais.


---

## ESTATÍSTICA INFERENCIAL (cont.) {.smaller-text}

**Métodos**** ****de**** ****inferência**** ****estatística**** ****para**** ****testes**** ****de**** ****hipóteses**

- 1) Inferências frequentistas (TSHN [Ho]; *p-**value*; *p** *< .05)
- 2) Estimação Bayesiana
- 3) Estimação por meio de *Bootstrapping*
(intervalo de confiança das diferenças/das magnitudes)


---

## ESTATÍSTICA INFERENCIAL (cont.) {.smaller-text}

**Testes**** ****de**** ****hipóteses**

Hipótese

- Uma expectativa sobre as características morfológicas de uma nova cultivar
- Ex: A cultivar Abacaxi BRS Ajubá apresenta maior nível de controle da fusariose que a cultivar BRS Vitória
- Teste de hipótese
- Avaliação, por meio de métodos científicos, a hipótese estabelecida.

---

## ESTATÍSTICA INFERENCIAL (cont.) {.smaller-text}

**Testes**** ****de**** ****hipóteses**

Passo a passo para o teste de hipóteses:

1) Crie uma ou mais hipóteses;

2) Colete dados úteis para testar as hipóteses criadas;

3) Análise seus dados com testes estatísticos adequados;

4) Avalie os resultados para ver se eles suportam as hipóteses iniciais.


---

## ESTATÍSTICA INFERENCIAL (cont.) {.smaller-text}

**Testes**** ****de**** ****hipóteses**

Ao coletar dados, você se depara com duas possibilidades:

Hipótese Nula (Ho) O efeito não existe

Hipótese Alternativa (Ha) O efeito existe


---

## ESTATÍSTICA INFERENCIAL (cont.) {.smaller-text}

**Testes**** ****de**** ****hipóteses**

Erro Tipo I: Rejeito a hipótese nula (Ho), quando Ho é verdadeira;

  - Afirmo que há efeito, quando não há
Erro Tipo II: Aceito a hipótese nula (Ho) ; quando Ho é falsa

  - Afirmo que não há efeito, quando há
**Verdadeira**

**Falsa**

**Rejeito**

**Aceito**


| Erro Tipo I | OK |
| --- | --- |
| OK | Erro Tipo II |


---

## ESTATÍSTICA INFERENCIAL (cont.) {.smaller-text}

**Testes**** ****de**** ****hipóteses**

Erro Tipo I: Rejeito a hipótese nula (Ho), quando Ho é verdadeira;

  - Afirmo que há efeito, quando não há
Erro Tipo II: Aceito a hipótese nula (Ho) ; quando Ho é falsa

  - Afirmo que não há efeito, quando há
Você está grávido!

Você não está grávida!


---

## ESTATÍSTICA INFERENCIAL (cont.) {.smaller-text}

**Inferência**** ****frequentista**** ****(valor-*****p*****)**

Ronald Fisher (1935)

  - Critério probabilístico objetivo (valor de
*p** *< 0,05)

  - Teste de significância da hipótese nula
(TSHN)


---

## ESTATÍSTICA INFERENCIAL (cont.) {.smaller-text}

**Inferência**** ****frequentista**** ****(valor-*****p*****)**

O critério do valor-*p** *de Fisher assume, arbitrariamente uma probabilidade de 5%

de chance de erro na inferência

Método de inferência estatística mais empregado na Psicologia


---

## ESTATÍSTICA INFERENCIAL (cont.) {.smaller-text}

**Inferência**** ****frequentista**** ****(valor-*****p*****)**

A cultivar Abacaxi BRS Ajubá apresenta maior nível (*M** *= 6,32; *DP** *= 1,33) de controle  da fusariose quando comparada a cultivar Abacaxi BRS Vitória(*M** *= 8.79; *DP** *= 1.19; *p** *< 0,05);


---

## ESTATÍSTICA INFERENCIAL (cont.) {.smaller-text}

**Inferência**** ****frequentista**** ****(valor-*****p*****)**

Todas as vezes que fazemos uma análise inferencial, você avalia se o efeito foi

estatisticamente significativo (*p** *< 0,05)

  - Vetiver com sistema radicular maior que paspalum (*p** *< 0,05)
  - Depressão se associou com baixa motivação no laboratório (*p** *< 0,01)
  - Não houve associação entre consumo de maconha e perda de libido (*p** *= 0,18).
  - A associação entre consumo de maconha e diminuição na memória foi marginalmente significativa (*p** *= 0,06)

---

## ESTATÍSTICA INFERENCIAL (cont.) {.smaller-text}

**Inferência**** ****frequentista**** ****(valor-*****p*****)**

Frequentemente usamos o valor de p como forma de inferência estatística, mas precisamos ter alguns cuidados

  - O valor de p é fortemente influenciado pelo tamanho amostral
      - Quanto maior a amostra, maior é a chance de você encontrar valores de p < 0,05. (erro do tipo I)
      - Valor de p não reflete, por si só, a magnitude do achado (força)
      - *r = *0,245 , p = 0,495 (n = 10)
      - *r = *0,245 , p = 0,298 (n = 20)
      - *r = *0,245 , p = 0,086 (n = 50)
      - *r = *0,245 , p = 0,041 (n = 70)
      - *r = *0,245 , p = 0,003 (n = 150)

---

## ESTATÍSTICA INFERENCIAL (cont.) {.smaller-text}

**Erro**** ****Tipo**** ****II:**

  - Acatar a Ho, quando ela é falsa.
  - Probabilidade de erro aceitável: 0,20
Poder amostral

O poder de um experimento é a probabilidade de detectar um efeito do

tratamento, se estiver presente.

O efeito não existe

*p** *= 0,08

** probabilidade de detectar o efeito

1 - 0,20 = 0,80.

(Cohen, 1988, 1992)

35

30

25

20

15

10

5

0

BRS Ajubá

BRS Vitória


---

## ESTATÍSTICA INFERENCIAL (cont.) {.smaller-text}

**Relação**** ****direta**** ****entre**** ****** **(significância)**** ****e**** ** **(poder *****b*****)**

  - 0.05 e 0.80 são os valores mais comumente aceitos na literatura
**Amostra**

**Pequena**

**Grande**

**Pequeno (****sig****)**

**Grande (n-****sig****)**

**Valor de p**

**Efeito alto**

**Efeito baixo **

**Efeito alto (erro tipo II)**

**Efeito alto**

**Efeito alto **

**Efeito baixo (erro tipo I)**


---

## ESTATÍSTICA INFERENCIAL (cont.) {.smaller-text}

**Outras situações que nos leva a cometer Erro Tipo I e Erro ****Tipo II**

Pressupostos dos testes não acatados

Amostras problemáticas (vieses de seleção)

Instrumento de pesquisa ruim


---

## {.smaller-text}

TAMANHO DA AMOSTRA


---

## TAMANHO DA AMOSTRA {.smaller-text}

**Erro Tipo I**

  - Efeito existe quando na verdade não: (a = 0,05)
  - **Erro Tipo II**
  - **Efeito não existe quando na verdade existe.**
  - **Poder amostral**
    - Poder = 1 - Beta (Prob. de Erro Tipo II) (1 - 0,20) = 0,80

---

## TAMANHO DA AMOSTRA (cont.) {.smaller-text}

**Tamanho do efeito **

O 𝑑𝑧​  é uma medida padronizada da diferença entre duas condições em um estudo de medidas repetidas.

**𝑑𝑧: **quanto maior, mais facilmente detectável é a diferença, necessitando de menos amostras.

**Erro Tipo I**

  - Efeito existe quando na verdade não: (a = 0,05)
  - **Poder amostral**
    - Poder = 1 - Beta (Prob. de Erro Tipo II) (1 - 0,20) = 0,80
    - Baixar G*Power

# [DISTRIBUIÇÃO NORMAL]{.section-header}

## DISTRIBUIÇÃO NORMAL (cont.) {.smaller-text}

O que é

- A Distribuição Normal é uma das distribuições de
probabilidade mais utilizadas para modelar fenômenos naturais.

- Isso se deve ao fato de que um grande número de fenômenos naturais apresenta esse tipo de distribuição.

---

## DISTRIBUIÇÃO NORMAL (cont.) {.smaller-text}

Como acontece

Como acontece a distribuição normal


---

## DISTRIBUIÇÃO NORMAL (cont.) {.smaller-text}

O que é

- A curva normal representa a forma como diferentes valores se agrupam em torno de um determinado ponto.
- A forma como diferentes pessoas se agrupam em torno de determinada
pontuação ou escore, para uma determinada variável.


---

## DISTRIBUIÇÃO NORMAL (cont.) {.smaller-text}

O que é

- A curva normal é definida por meio de duas informações: média e desvio-padrão
- Tamanho radicular Capim vetier
- Média: 76,62cm
- Desvio-Padrão: 3,72cm

---

## DISTRIBUIÇÃO NORMAL (cont.) {.smaller-text}

Média

Média = 613 = 76,62

8


| 55 | 64 | 72 | 80 | 70 | 100 | 98 | 74 |
| --- | --- | --- | --- | --- | --- | --- | --- |


---

## DISTRIBUIÇÃO NORMAL (cont.) {.smaller-text}

Desvio-Padrão

Estimativa de variabilidade em torno da média

Média

76cm

245 = 15,66

7


| 55 | 64 | 70 | 72 | 74 | 80 | 98 | 100 |
| --- | --- | --- | --- | --- | --- | --- | --- |


---

## DISTRIBUIÇÃO NORMAL (cont.) {.smaller-text}

A curva normal é definida por meio de duas informações: média e desvio-padrão

Média = 170; DP = 5,72

Frequência (*n)*

+-1 DP (68.3%) = [164,28- 175,72]

+-2 DP (95,4%) = [158,56- 181,44]

+-3 DP (99,7%) = [152,84 - 187,16]


---

## DISTRIBUIÇÃO NORMAL (cont.) {.smaller-text}

DESVIOS DE DISTRIBUIÇÃO DE NORMALIDADE

Renda no Brasil

Mais pobres

Mais ricos

Quantidade de pessoas

Renda


---

## DISTRIBUIÇÃO NORMAL (cont.) {.smaller-text}

DESVIOS DE DISTRIBUIÇÃO DE NORMALIDADE

DESVIO POR ASSIMETRIA


---

## DISTRIBUIÇÃO NORMAL (cont.) {.smaller-text}

DESVIOS DE DISTRIBUIÇÃO DE NORMALIDADE

DESVIO POR CURTOSE

**Leptocúrtica**: Dados muito concentrados junto à media;

**Mesocúrtica**: Distribuição normal

**Platicúrtica**: Dados muito dispersos; muitas pessoas muito afastadas da média.


---

## {.smaller-text}

TESTANDO A DISTRIBUIÇÃO NORMAL NO JASP

Luiz Diego Vidal - vidal.center@academico.ufs.br - CPF: 033.281.915-93


---

## DISTRIBUIÇÃO NORMAL (cont.) {.smaller-text}

COMO SABER SE SEUS DADOS SÃO NORMALMENTE DISTRIBUÍDOS?

**Critérios**** ****descritivos**** (****Tabachnick**** ****and**** ****Fidell****, 2019)**

Transforme o escore da Assimetria e Curtose em escore Z

Calcule: Assimetria e Curtose / Erro padrão

Valor maior que |1.96| é significativo *p** *< .05

Valor acima que |2.58| é significativo *p** *< .01

Valor acima que |3.29| é significativo *p** *< .001


---

## DISTRIBUIÇÃO NORMAL (cont.) {.smaller-text}

COMO SABER SE SEUS DADOS SÃO NORMALMENTE DISTRIBUÍDOS?

**Critérios**** ****estatísticos**** ****(**Testes de significância)

  - Kolmogorov-Smirnov e Shapiro-Wilk
  - Hipotese nula: Dados não são normalmente distribuídos
Espera-se rejeitar a hipótese nula → Dados são normalmente distribuídos

  - Nos testes de K-S e S-W, espera-se que *p** *> 0,05 (maior que) para acatar a distribuição de
normalidade dos dados.


---

## DISTRIBUIÇÃO NORMAL (cont.) {.smaller-text}

QUAIS DOS TESTES ESTATÍSTICOS UTILIZAR?

  - Shapiro-Wilk  > Anderson-Darling >  Kolmogorov-Smirnov (Liliefors) > Kolmogorov-Smirnov

# [TAMANHO AMOSTRAL]{.section-header}

# {background-color="#034EA2"}

[Obrigado!]{.obrigado-fit-text style="color: white;"}

::: {style="text-align: center; color: white; font-size: 0.7em;"}
Luiz Diego Vidal Santos

Universidade Estadual de Feira de Santana (UEFS)
:::

