---
title: "Taxonomia de Bloom"
subtitle: "Níveis de Aprendizagem e Pesquisa<br>Análise de Dados Ambientais"
author: "Luiz Diego Vidal Santos"
institute: "Universidade Estadual de Feira de Santana (UEFS)"
format:
  revealjs:
    logo: ../../assets/logo-uefs.webp
    footer: "UEFS | Análise de Dados Ambientais | Taxonomia de Bloom"
    slide-number: true
    theme: [simple, ../../assets/uefs.scss]
    controls: true
    width: 1280
    height: 720
    css: ../../assets/custom.css
    transition: slide
    background-transition: fade
    preview-links: auto
execute:
  echo: false
---

## {.smaller-text}

TAXONOMIA DE BLOOM


---

## OBJETIVO INICIAL {.smaller-text}

A Taxonomia de Bloom foi criada para classificar objetivos educacionais e facilitar o ensino, a aprendizagem e o desenvolvimento cognitivo.

Forneça uma linguagem clara e compartilhada para objetivos de aprendizagem


---

## A ESCOLHA DA ANÁLISE {.smaller-text}

**Pergunta/hipótese**

Isso precisa ser feito para todos os seus objetivos e perguntas de pesquisa


| Pergunta | Hipótese | Análise a ser realizada |
| --- | --- | --- |
| Filhos de pais separados têm maior nível de ansiedade do que filhos de pais casados? | Não há diferença nos níveis de ansiedade entre filhos de pais separados e filhos de pais casados |  |
| Qual a característica da personalidade prediz com maior força, o perfil de risco que sujeitos adotam nos seus investimentos? | Abertura de experiência é um principal preditor do perfil de risco. |  |
| Exercícios aeróbicos são mais eficientes na queima de gordura que exercícios anaeróbicos? | Exercícios anaeróbicos são mais eficientes do que exercícios aeróbicos. |  |


---

## A ESCOLHA DA ANÁLISE (cont.) {.smaller-text}

De acordo com Stevens (1946), as variáveis podem ser classificadas como:

Normal

Ordinal

Escalar

Razão

O tipo de variável determina a análise a ser utilizada


---

## VARIÁVEIS NOMINAIS {.smaller-text}

**Uma variável totalmente qualitativa**

  - Não significa que não pode ser feita análises quantitativas
**Os valores apenas diferenciam categorias qualitativas diferentes, mas não há relação entre as categorias.**

Ex: nacionalidade, religião, estado civil

**Os números atribuídos não tem significado matemático.**

  - Brasileiro
  - Argentino
  - Chinês

---

## VARIÁVEIS ORDINAIS {.smaller-text}

**Há uma diferença entre as categorias**

  - Estabelece uma ordem ou hierarquia entre as categorias.
  - No entanto, o intervalo entre as categorias não é regular.
*A ordem de chegada dos corredores na linha de chegada é um exemplo de medida ordinal, Você sabe quem chegou primeiro, mas o dado por si só não informa se a diferença do segundo foi de um segundo ou uma hora*

**Escolaridade**

1) Ensino fundamental; 2) Ensino médio; 3) Ensino superior


---

## VARIÁVEIS ORDINAIS (cont.) {.smaller-text}

**Escalas Likert**


| Discordo totalmente | Discordo | Nem concordo nem discordo | Concordo | Concordo totalmente |
| --- | --- | --- | --- | --- |
| 1 | 2 | 3 | 4 | 5 |


---

## VARIÁVEIS ESCALARES E DE RAZÃO {.smaller-text}

**O intervalado entre os valores é sempre constante.**

**O que diferencia a variável escalar e razão é o significado do valor 0.**

**Zero da escala intervalar é um valor arbitrário.**

0º C;

A nota de um teste de matemática pode ser uma medida intervalar:

Cada unidade da nota corresponde a uma questão correta.

Entretanto, uma nota zero não corresponde a ausência de conhecimento matemático.


---

## VARIÁVEIS ESCALARES E DE RAZÃO (cont.) {.smaller-text}

**Escala de Razão.**

**O valor zero significa total ausência do atributo mensurado**

Segundos

SalárioVolume de vendas

Distâncias

A maioria das análises nas ciências humanas, sociais e da saúde usam dados ordinais ou escalares


---

## VARIÁVEIS ESCALARES E DE RAZÃO (cont.) {.smaller-text}

**Procedimentos de análises**


| Nível de medida | Propriedades |
| --- | --- |
| Nominal | Distinção |
| Ordinal | Distinção + Ordem |
| EscalarRazão | Distinção + Ordem + Distância |


---

## CLASSIFICAÇÃO {.smaller-text}

**Classificação Problemática**


---

## CLASSIFICAÇÃO (cont.) {.smaller-text}

**Classificação Adequada**

*** Específico **

**para escala ****likert**


---

## VARIÁVEIS ESCALARES E DE RAZÃO {.smaller-text}

**Por que tratamos a escala Likert como variável contínua?**

Mínimo: 4 e máximo: 20


| Item | Discordo totalmente | Discordo | Nem concordo nem discordo | Concordo | Concordo totalmente |
| --- | --- | --- | --- | --- | --- |
| Item 1 | 1 | 2 | 3 | 4 | 5 |
| Item 2 | 1 | 2 | 3 | 4 | 5 |
| Item 3 | 1 | 2 | 3 | 4 | 5 |
| Item 4 | 1 | 2 | 3 | 4 | 5 |


---

## VARIÁVEIS ESCALARES E DE RAZÃO (cont.) {.smaller-text}

**Por que tratamos a escala Likert como variável contínua?**


# {background-color="#034EA2"}

[Obrigado!]{.obrigado-fit-text style="color: white;"}

::: {style="text-align: center; color: white; font-size: 0.7em;"}
Luiz Diego Vidal Santos

Universidade Estadual de Feira de Santana (UEFS)
:::

