---
title: "Adaptação de Instrumentos de Medida"
subtitle: "Tradução e Adaptação Transcultural<br>Análise de Dados Ambientais"
author: "Luiz Diego Vidal Santos"
institute: "Universidade Estadual de Feira de Santana (UEFS)"
format:
  revealjs:
    logo: ../../assets/logo-uefs.webp
    footer: "UEFS | Análise de Dados Ambientais | Adaptação de Instrumentos de Medida"
    slide-number: true
    theme: [simple, ../../assets/uefs.scss]
    controls: true
    width: 1280
    height: 720
    css: ../../assets/custom.css
    transition: slide
    background-transition: fade
    preview-links: auto
execute:
  echo: false
---

# [ADAPTAÇÃO]{.section-header}

## ADAPTAÇÃO {.smaller-text}

DE INSTRUMENTOS DE AUTORRELATO


---

## {.smaller-text}

ADAPTAÇÃO DE INSTRUMENTOS

O que vamos aprender

  - Adaptação não é tradução
  - Tradução
  - Síntese da tradução
  - Avaliação por comitê de experts & público-alvo
  - Back Translation

---

## {.smaller-text}

Adaptar não é traduzir

O processo adaptação é muito mais completo que a tradução;

Um processo errado na adaptação dos itens pode resultar em frases incompreensíveis ou não coerente com o idioma-alvo (Hambleton, 1994)

ADAPTAÇÃO DE INSTRUMENTOS


---

## {.smaller-text}

TRADUÇÕES

Dois tradutores, visando minimizar o risco de vieses linguísticos, psicológicos, culturais e de compreensão teórica e prática (Cassepp-Borges, Balbinotti, & Teodoro, 2010).

**Qualidade dos tradutores**

  - Fluentes no idioma de origem do instrumento e **nativos no idioma-alvo**.
    - Considerar as nuances do idioma para o qual o instrumento se destina
    - Maior adequação cultural da adaptação.
  - Tradutor 1: Familiaridade com o construto avaliado → Foco em maior rigor científico
  - Tradutor 2: Pessoa da população geral, sem conhecimento de Psicometria → Foco na linguagem usada pela população geral.
ADAPTAÇÃO DE INSTRUMENTOS


---

## {.smaller-text}

SÍNTESE DAS TRADUÇÕES

Síntese das Traduções

Refere-se ao processo de comparar as diferentes traduções e avaliar as suas discrepâncias semânticas, idiomáticas, conceituais, linguísticos e contextuais, com o objetivo de se chegar  a uma versão única.

ADAPTAÇÃO DE INSTRUMENTOS


---

## {.smaller-text}

SÍNTESE DAS TRADUÇÕES

**Fontes de complicações:**

  - Traduções erradas
  - Traduções complexas e rebuscadas
  - Traduções demasiadamente simplistas que subestimam o conteúdo do item
  - Traduções que não respeitam a ‘linguagem falada’, com o uso de termos e expressões pouco comuns
na ‘vida real’

- Em geral, quem traduz, busca traduzir ao pé da letra.
- No processo da síntese é que acontece o primeiro passo da ‘adaptação cultural’
ADAPTAÇÃO DE INSTRUMENTOS


---

## {.smaller-text}

SÍNTESE DAS TRADUÇÕES

**Quem faz a síntese?**

  - Autor do estudo e equipe de pesquisa.
**O que deve ser avaliado?**

  - **1) Equivalência semântica: **Se o item apresenta o mesmo significado do original e se existem erros gramaticais na tradução
  - **2) Equivalência idiomática: **Refere-se a avaliar se os itens de difícil tradução do instrumento original foram adaptados por uma expressão equivalente que não tenha mudado o significado cultural do item
  - **3) Equivalência experiencial: **Refere-se a observar se determinado item de um instrumento é aplicável
na nova cultura, e em caso negativo, substituir por algum item/conteúdo equivalente

  - **4) Equivalência conceitual: **Busca avaliar se determinado termo ou expressão, mesmo que traduzido adequadamente, avalia o mesmo aspecto em diferentes culturas
ADAPTAÇÃO DE INSTRUMENTOS


---

## {.smaller-text}

SÍNTESE DAS TRADUÇÕES

**Ainda sobre o processo de síntese**

  - Em caso de falhas e limitações nas traduções, o comitê pode propor uma nova adaptação, que seja
mais adequada às características do instrumento e à realidade onde o mesmo será utilizado.

  - **Atenção**: A participação dos autores responsáveis pela tradução do instrumento é fundamental, visto que estes devem possuir conhecimento suficiente sobre o construto que o instrumento avalia.
  - É **normal **que ao final do processo, o pesquisador tenha:
    - a) Alguns itens do Tradutor 1 e outros do Tradutor 2
    - b) Itens mesclados (parte do Tradutor A e parte do Tradutor B)
    - c) Itens modificados e redigidos pela equipe
    - **VER FICHA**
ADAPTAÇÃO DE INSTRUMENTOS


---

## {.smaller-text}

**Ainda**** ****sobre**** ****o**** ****processo**** ****de**** ****síntese**

  - Comitê  de  *experts**  *na  área  da  avaliação psicológica, ou, se possível, na área específica do instrumento;
  - Avaliará aspectos ainda não contemplados, tais como a estrutura, o *layout,** *as instruções do instrumento e a abrangência e adequação das expressões contidas nos itens.
  - Termos ou expressões podem ser generalizados para diferentes contextos e populações?
  - As expressões são adequadas para aquele público a que o instrumento se destina?
ADAPTAÇÃO DE INSTRUMENTOS


---

## {.smaller-text}

AVALIAÇÃO DA SÍNTESE

**Cuidados adicionais com populações**

  - Crianças
  - Idosos
  - Aspectos  da  diagramação  são  tão  imprescindíveis quanto os aspectos linguísticos dos itens
  - A clareza do *rapport*, a adequação do tipo e tamanho da fonte utilizada, a disposição das informações no instrumento, etc.
ADAPTAÇÃO DE INSTRUMENTOS


---

## {.smaller-text}

Verificar se as sentenças, as instruções e a escala de resposta são compreensíveis para o público alvo.

ADAPTAÇÃO DE INSTRUMENTOS


---

## {.smaller-text}

Verificar se as sentenças, as instruções e a escala de resposta são compreensíveis para o público alvo.

As instruções são claras?

Os termos presentes nos itens estão adequados?

As expressões correspondem àquelas utilizadas pelo grupo?

Os sujeitos a participarem desta etapa podem variar de acordo com as características dos respondentes a que o instrumento se destina.

  - Escolaridade, regiões do país, etc.
ADAPTAÇÃO DE INSTRUMENTOS


---

## {.smaller-text}

AVALIAÇÃO PELA POPULAÇÃO ALVO

**FICHA DO PILOTO COM A POPULAÇÃO ALVO**

  - Mudanças substanciais devem ser reavaliadas pela população-alvo
  - Caso não hajam modificações importantes, passa-se para a próxima etapa, de tradução reversa.
ADAPTAÇÃO DE INSTRUMENTOS


---

## {.smaller-text}

BACK-TRANSLATION


---

## {.smaller-text}

BACK-TRANSLATION

Tradução Reversa

  - Trata-se de um procedimento onde o instrumento adaptado é traduzido de volta para a
linguagem original

  - Possibilita que o autor da versão original avalie a qualidade da versão adaptada
  - Verificação de controle de qualidade adicional (Sireci et al., 2006).
  - Seu objetivo é avaliar se/em que medida o processo de adaptação mudou o significado do item, conforme propõe a versão original.
  - Deve suceder todos os procedimentos de ajuste semântico e idiomático
    - O instrumento, nesta etapa, deverá estar “pronto” para avaliação final do autor do 	instrumento original.
Back-translation


---

## {.smaller-text}

BACK-TRANSLATION

Cuidados com a tradução reversa

  - Procedimento que requer cautela (Gudmundsson, 2009; Hambleton, 1993; Van de Vijver & Leung, 1997).
  - **Crítica:****	**a	lógica	da	tradução-reversa	desconsidera	o	que	até	então	vem	sendo preconizado:
    - Ao	adaptar	um	instrumento,	diversos	aspectos,	sejam	eles	culturais,	idiomáticos, 	linguísticos e contextuais, precisam ser considerados.
    - Se fazemos uma série de adaptações culturais no item, qual o sentido de traduzir ele 	de volta para a linguagem original?
Back-translation


---

## {.smaller-text}

BACK-TRANSLATION

**Quem**** ****faz**** ****a**** ****back-****translation?**

  - Dois tradutores que não aqueles que realizaram a primeira tradução (Beaton et
al., 2000).

**Qualidade**** ****dos**** ****tradutores**

  - Um nativo no idioma alvo do instrumento (Brasileiro fluente em inglês)
  - Um nativo no idioma de origem do instrumento (Americano, fluente em português).
    - É importante ter ao menos um nativo para que a retrotradução seja o mais correta e usual possível (i.e., gramaticalmente correta e adequada de acordo com o padrão de uso da língua)
Back-translation


---

## {.smaller-text}

BACK-TRANSLATION

Cuidados com a tradução reversa

  - O objetivo da tradução reversa não deve ser a obtenção de uma equivalência literal entre as versões
  - Ferramenta para identificar palavras que não ficaram claras na língua-alvo, inconsistências ou erros conceituais na versão final
Os autores do instrumento original nem sempre entendem isso

Back-translation


---

## {.smaller-text}

ESTUDO-PILOTO

Estudo-piloto qualitativo (avaliação da população-alvo)

Estudo piloto quantitativo?

  - Análise de dados com N baixo é problemático
  - Se acontecer um problema, o problema está na medida ou no *N*?
Back-translation


# {background-color="#034EA2"}

[Obrigado!]{.obrigado-fit-text style="color: white;"}

::: {style="text-align: center; color: white; font-size: 0.7em;"}
Luiz Diego Vidal Santos

Universidade Estadual de Feira de Santana (UEFS)
:::

