%%{init: {'theme':'base', 'themeVariables': { 'primaryColor':'#003366','primaryTextColor':'#fff','primaryBorderColor':'#00A859','lineColor':'#0066CC','secondaryColor':'#00A859','tertiaryColor':'#fff','background':'transparent'}}}%%
mindmap
  root((Ecossistema<br/>SE))
    Universidades
      UFS
        Agitte.se
        CISE
        Laboratórios
      IFS
      UNIT
    Governo
      FAPITEC-SE
        Editais
        Bolsas
      SEDETEC
        Políticas
    Empresas
      Startups
        TechSE
        InovaSE
      Indústrias
        Petrobras
        Vale
    Infraestrutura
      CISE::UFS
      Sergipetec
      Porto Digital