---
title: "Declividade – Equipamentos"
subtitle: "Aspectos Metodológicos e Instrumentos de Medição<br>Bioengenharia de Solos"
author: "Luiz Diego Vidal Santos"
institute: "Universidade Estadual de Feira de Santana (UEFS)"
format:
  revealjs:
    logo: ../../../assets/logo-uefs.webp
    footer: "UEFS | Bioengenharia de Solos | Declividade – Equipamentos"
    slide-number: true
    theme: [simple, ../../../assets/uefs.scss]
    controls: true
    width: 1280
    height: 720
    css: ../../../assets/custom.css
    transition: slide
    background-transition: fade
    preview-links: auto
execute:
  echo: false
---

# [Disciplina: anejo e Conservação da gua e do Solo]{.section-header}

## Disciplina: anejo e Conservação da gua e do Solo {.smaller-text}

**DECLIVIDADE– Aspectos metodológicos e Equipamentos**


|  | UNIVERSIDADE FEDERAL DE SERGIPE – UFS
CENTRO DE CIÊNCIAS AGRÁRIAS APLICADAS - CCAA
DEPARTAENTO DE ENGENHARIA AGRONICA - DEA |
| --- | --- |


---

## {.smaller-text}

::: {.callout-note}
Slide original contém 1 imagem(ns) ilustrativa(s).
:::

**Declividade do solo**

A **declividade** é a inclinação da superfície do terreno em relação à horizontal, ou seja, a relação entre a diferença de altura entre dois pontos e a distncia horizontal entre esses pontos.  dada em graus e em porcentagem.


---

## {.smaller-text}

::: {.callout-note}
Slide original contém 1 imagem(ns) ilustrativa(s).
:::

D= (V1+V2+V3+V4)/(4 * 3m) * 100

D= ((L1-L2) + (L3-L4) + (L5-L6)... (Ln – Ln+1))/ H1+H2+ H3... + Hn)) *100


---

## {.smaller-text}

::: {.callout-note}
Slide original contém 6 imagem(ns) ilustrativa(s).
:::

**Passo a passo na confecção do Pé-de-Galinha (retangular)**


---

## {.smaller-text}

::: {.callout-note}
Slide original contém 6 imagem(ns) ilustrativa(s).
:::

**Passo a passo na confecção do Nivel de Borracha ou Nivel de angueira**


---

## {.smaller-text}

Clculo de Declividade:

**Nivel de Borracha**

**D= EV/EH * 100    L1=32,0cm; L2=23,0 cm; L3=38,0 cm; L4=21,0 cm;**

**L5=28,0 cm; L6=19,8cm; L7=25,9cm e L8=22,3cm**

**(L1-L2) + (L3-L4)  +( L5-L6) + (L7-L8)**

**9 + 17 + 8,2 + 3,6  = 37,8 = EV**

**H1= 12m; H2=8m; H3= 11m; H4=15m  = **

**D=(EV/EH)*100**

**D= (EV)/(EH) * 100 = (37,8cm/46m)  = 0,82%**

**Pé-de-galinha    EV=(EV1 + EV2 + EV3 + ....+ EV6/ 6 x 3) = **

**D= EV/EH * 100**

**EV1= 4cm; EV2=8cm; EV3; 5cm; EV4=10cm; EV5=8cm; EV6=7cm**

**D=(EV/EH)*100**

**D= (42cm/18m) = 2,33%**

D= ((L1-L2) + (L3-L4) + (L5-L6)... (Ln – Ln+1))/ H1+H2+ H3... + Hn)) *100


# {background-color="#034EA2"}

[Obrigado!]{.obrigado-fit-text style="color: white;"}

::: {style="text-align: center; color: white; font-size: 0.7em;"}
Luiz Diego Vidal Santos

Universidade Estadual de Feira de Santana (UEFS)
:::
