project:
  type: default
format:
  revealjs:
    theme: [simple, ../../assets/uefs.scss]
    css: ../../assets/custom.css
    width: 1280
    height: 720
    transition: none
    background-transition: none
    preview-links: auto
    slide-number: true
    controls: true
    controls-layout: bottom-right
    touch: true
    navigation-mode: linear
    embed-resources: true
    auto-stretch: false
    min-scale: 0.2
    max-scale: 2.0
    margin: 0.04
    scrollable: true
    view-distance: 1
    mobile-view-distance: 1
    menu: false
    logo: ../../assets/logo-uefs.webp
    footer: "DCHF-UEFS | Análise Ambiental | Prof. Diego Vidal"
    include-after-body:
      - ../../assets/image-lightbox.html
      - ../../assets/progress-bar.html
