---
title: "Publicações Acadêmicas"
---

Lista de publicações acadêmicas de **Luiz Diego Vidal Santos**. Para informações completas e atualizadas, consulte:

- {{< ai orcid >}} [ORCID — 0000-0001-8659-8557](https://orcid.org/0000-0001-8659-8557)
- {{< fa graduation-cap >}} [Plataforma Lattes](http://lattes.cnpq.br/7491112603328096)

::: {.callout-tip}
## Nota
Esta lista foi gerada automaticamente a partir do OCR do Currículo Lattes e pode conter erros de digitação.
:::

## Artigos completos em periódicos
- EBBMOANDA, FS. R; CASTRO, 1.0.5; SANTOS, L. D.V. SANTOS LOM ANDRADE C. EC, GRIZA, 5; RODRIGUES JUNIOR, 1 1; Padoti Au. Doradaton ol getotis cf Tinha Lato in (ad o cenginarma acaigues, CIENCIA FLORESTAL (ONLINE) JOR, V3, PO! 14, 2020 Ciiações: nar E SSEE "S/S GSPUS?
- CARVALHO. A nt: SANTOS, L. D. V: SANTOS, LO. HOLANDA. E 5 R: Potro, aco Amt G. M DIGITAL INAGE PROCESSING FOR EVALUATION OP PASPALUM MLLEGRANA. SOMRÃD ROOT SYSTEM. Rovisia Gacinga. JR, 3, 100 107, 2020.
- EBBSANTOS, LD; SANTOS, LO V: ENES, AM: HOLANDA, E 5. R; SANTANA. CO. Pesto Acou: JESUS, AN. BANDEIRA À. Asiação do comportamento do Blospocie em ieranes bos do unida do Elo, Brailandoumal Gi Devlepenor. VP 289 - 52508, 2020 EBBANORADE CE CG: LIMANETO E G: HOLANDA F 5. R; SANTOS, LUIZ DIEGO VIDAL: BANDEIRA À, Ananias ol varal leme to dl artes kords. he sa ot VO Sia lo! apple t t8cnclog ane fl cel INTERNATIONAL JOURNAL FOR INNOVATION EDUCATION ANO RESEARCH. vo, p287, 2020
- SANTOS, L.D. V. SANTOS, LD HOLANDA, E 5. R:ANORADE, CEC; BANDEIRA A: Pego, Alcou. Lava &s mãos mas o o acesso à água? Brosnaoção teológica sobre PDA em Recassns Hitfcos. Rosi nero emencana de Clncas Ambient. p.29 46, 2020
- EBBSANTOS, LON SANTOS. LO V: HOLANDA, E SR; SANTANA, C. O. Vi; ANORADE CE Pose, Ao Mineração das prooadades dust cionacas noso agrêna no Bra San Jul ot Anal an Envemo esemon 3 pot? = 11872020
- SANTOS, LUIZ DIEGO VIDAL: ENES, A M: HOLANDA ES. R: SANTOS, 1.18. ANORADE, CEC. SANTOS, C. O, Processamento Diga de Imagem na nvestgação de camnhaménto do cipa nasutames comgr [nsect isopita) Rea Eras de Holo Ambiente Cap NO2 MO, d02
- SANTOS, L.D, V; SANTOS LD HOLANDA, E 5.R;ANORADE, CEC; TEMERA E 15 Pego, Alcou: Saos. . Progpgcção de peotos dracenados à cegurança nos procedimentos e esmo em lnques alone do armazenamento de combustuis em posts de revenda NATURE AND CONSERVATION. 13, .113 122, 2020
- Santos MS; HOLANDA. FS. R: SANTOS, LD. SANTOS, LD. V: Saco A P:UMA F Peleepção sobr indicadores tcnclgios, susestávels e ambieti do imo Rua do bao São. Francáco(SE. avise INGI- Indicação Geográic o Inação 4, 595, 2018
- EMBSANTOS, LUIZ DIEGO VIDAL: HOLANDA, FRANCISCO SANDRO RODRIGUES, FILHO, JBCKSON JOSE MENEZES BARBOSA. OLIVEIRA, WILIVAN FARIAS; DA SLVA, EMERSON GUEDES, BUSSUCH ELIANA NIDORI GRIZA, SANDRO! DE MENEZES, CRISTIANO TELES. Anais faro enaracdtes an biodsradato esistanco natural Rss geststas from Tia domingensis, Elecepane ep na Syagrus corona under uterina Res. Dicove Rpplaa Seinees. ví, 7 761, oz
- EBEISANTOS, JÉSSICA NARCY SILVA MELO; LUCAS, ARIOVALDO ANTONIO TADEU; NETTO. ANTENOR OLIVEIRA AGUIAR: SILVA, IRON JOSÉ; SANTOS, LUIZ DIEGO VIDAL; CARVALHO, CAVTON MOURA DE. Characieizanên ol Diinage Water For San So Sol Be Sem Region Bra ROSA (ANPAD). v 19, p.e011620. 2026
- EMBSOUZA RM: SANTOS, LD.V. BEZERRA, MF L:SILVA, EMERSSON G; HOLANDA, FRANCISCO &, R, Esratáis para Conrla da Ertao Lear am Amania Topeai a Subtçicas, REVISTABRASKLEIRADE GEOGRAFIA FÍSICA vê, pari 280, 2025
- ERBARALJO FILHO. RN; FREIRE 8.6.5; FREIRE, FU; FERREIRA RL. Cs PEREIRA LM SANTOS, L. D. . LiorD namics and Nuriam Stocks na Chronocequence o Hypareroplous Forest Under ne Elec Cie Felina, Ecology and Evolution, JR, 15, p72 10, 2025
- ERBISANDEIRA, ARILMARAABADE, HOLANDA, FRANCISCO SANDRO RODRIGUES; SANTOS, LUIZ DIEGO VIDAL, ANDRADE, CARLOS EDUARDO CELESTINO DE. Mariz de Indicadores de Eênca e tenoloa relacionados de inovações no uso de iopolimeros poa setor da consirção cv REVISTA TECNOLOGIA E SOCIEDADE (ONE), JER 42190, 2025
- EMBNASCIENTO, SIDNEY CASSEMIRO DO; HOLANDA, FRANCISCO SANDRO RODRIGUES; FANHO, JOSÉ PAULO JESUS, SANTOS, LUIZ DIEGO VIDAL, PATENTOMETRIA RELACIONADA ATEONOLOGIA SG E A AGRICULTURA SUSTENTÁVEL: P2P & INOVAÇÃO. 12 pe-7652, 2025
- ERBISANTOS, JESSICAMARCY SILVA MELO; LUCAS, ARIOVALDO ANTONIO TADEU; NETTO, ANTENOR DE OLIVEIRA AGUIAR: SLVA, AIRON JOSÉ DA: SANTOS, LUIZ DIEGO VIDAL; CARVALHO, CLAVTON MOURA DE. Qualy Sodum-Salne Sol Drag Visor and se Cleiton fe Imgatan Purposos ita Brain Same Ava gm. ROSA (ANPAD) 18, 0012248, 2025
- ERBHOLANDA, FRANCISCO R.; SANTOS, LUIZ D. V; SUSSUCH, ELIANAM: Podot Acou SANTOS, JOSÉ F. SILVA, EMERSON: FONTES, CÁTIA 5 ARAUJO FILHO, RENISSONA, Resistanc or Syagnus ctonet fer hn walaeroot coa nal gets under enurermeni degradsionFronbers in Suiamabilty vô, p 1852269, 2028
- EBBSOUZA, RM; SANTOS, LON BEZERRA, MEL; SINA EG; HOLANDA E SR Statogos for Ligór Esso Cont in Tróplcaland Susto! Envioomenis. REVISTA BRASILEIRA DE” GEOGRAFIA ÍSICA 18, 2182 2600, 2026
- EBBISANTOS, LUIZ DIEGO VIDAL: HOLANDA, FS. R. Pocioti Aleou: SANTANA, CO. v: MEDEIROS, RR 8. An empircal mad or branding ori by re ervronmental susana time zo Ralleros a ori Sructual quaton modeling vin CA approsch. Dicovor Anis. 2 po
- EBBSANOEIRA, ARILMARA ABADE; SANDRO RODRIGUES HOLANDA, FRANCISCO; EDUARDO GELESTINO DE ANDRADE, CARLOS, DIEGO VIDAL SANTOS, LUIZ. ANÁLISE PATENTOMÉTRICA. SOBRE AS INOVAÇÕES QUE TEM CONO BASE O USO DE BIOPOLÍVEROS PELA CONSTRUÇÃO CAM BATENTOVE TRIO ANALYSIS OF INNOVATIONS SASED ON THE USE OF BIOPOLVHERS IN CML CONSTRUCTIONANÁLISES DE PATENTES SOBRE INNOVACICNES BASADO EN EL USO DE BIOPOLÍMEROS EN CONSTRUCCION CIVILANÁLISE PATENTOMETRICA SOBRE AS INOVAÇÕES QUE TÉM COMO BASE O USO DE BIOPOLÍMEROS PELA CONSTRUÇÃO CML RECIMAZ! “Rita ClemcaNútdscpdnar ISSN 28756218, vê, pa511S054, 2024 a EA “ EBBcones Cr. VIDAL, LUIZ DIEGO; HOLANDA, F.S.R. SANTANA C.0.U, SINA, E 6. PINENTANETO, À L A; FONTES FILHO, E O. Aesegementol he entrapranevral iianton é unmersty Eder using rave methodology OBSERVATÓRIO DE LA ECONOMIA LATINOAMERICANA 12. Paress -Sr6t5, 2024 GOMES
- F; SANTOS, LO HOLANDA F 5. R; OLIVEIRA CV. 5; SVA EG; PIMENTANETO, ALA FONTES FLHO, E O. Ascesement cl ta entoprenaualterion of Unvaray sudrts using Fasch metodo OBSERVATÓRIO DE LA ECONOMIA UATINOAMERICANA, 22, p.7675, 2028
- SANTOS, LUIZ DIEGO VIDAL: HOLANDA, FRANCISCO SANDRO RODRIGUES; Post, Ala: NO, JARISSON BISPO; DOS SANTOS FONTES, CATIA: DE MELO, JEANGELA CARLA RODRIGUES, MARINO, REGINA HELENA, BOGE, GIZELIO MENZES, Geográ pe getetie made. From Tha domngonss fes uh hgh tens srt or raio caio. Inventor Dicoira vt pNOOUAS, 2024
- SANTOS, 1.4, Pestots Alceu. HOLANDA, FS. R; SANTOS, LD. U; ANORADE 6.14 ARAÚJO FILHO, RN. Impact or tha lag elemento produce o gran com [258 mays LJ Ion lm post Northeast ra. SON USE AND MANAGEMENT. JE, 4.40, 014061, 2324 Clações: ão Cr Sente OS copus 1
- HOLANDA, FRANCISCO SANDRO RODRIGUES; VIDAL SANTOS, LUIZ DIEGO; 1410 ARAÚJO FILHO, RENISSON NEPONUCENO DE: NASCIMENTO, BRENNO LIM, rfuanea ci Sodium todo Treme on lr or Gooloie Hlrulactung, AOS Omega, JR, 1, 4GDSBO2, 2024 EEE soLANo, FRANCISCO SANDRO RODRIGUES; SANTOS, LUIZ DIEGO VIDAL. ELO. JEBNSELA CARLA RODRIGUES DE. OG, GEO MENEZES SUSSUCH, ELIANA MiDOR NASCIMENTO, BRENNO LINA. SANTOS, MÁRICOS VINÍCIUS QUIRINO DOS; OLIVEIRA, MARIA. TERAFIM UENBE DE. Rectanc cf ho fber-ervoa gota om TionaGomingonsis subo to fel degraatio. Sit Report. IR. v14, 0648, 2024
- MOLANDA, FS R SANTOS, L.D. V; MELO
- C R;SANTOS LS; PEDRO A SUSSUCH E Ni; GRIZA
- Compation of mechanical peiomanco cdfirat goctostos. anular tom natal er sulco emvronmentlbodegraêator, INTERNATIONAL JOURNAL DE ADVANCED MANUFACTURINO TECANOLOGY. JR, p 1254 2025. ações: rt 0 icence» à iscapuS?
- SANTOS, LUIZ DIEGO VIDAL; HOLANDA, FRANCISCO SANDRO RODRIGUES; OLIVEIRA, CATUXE VARURO DE SANTANA: MENEZES, PEDRO VINÍCIUS BERTULINO DE: PEDROTT! A VRLWOCK, À. PS, Consumer perco ci brand equi Based on anvromnia susaapat developmert an validate OF a Sede, OBSERVATORIO DE LR ECONOMIA LATINOAMERICANA, v21, Dae Neo 2020 EERVIDAL SANTOS, LUIZ DIEGO; RODRIGUES HOLANDA. FRANCISCO SANDRO; DE MENEZES, PEDRO VINÍCIUS BERTULINO: DE SANTANA OLIVEIRA, CATUXE VARJÃO; SOMERVINSA VILAMOCK, ANA PAULA, Pedro Aco. Nou cometa been Brand ar êmronmantay sustainable bushessos ln ne Amázon 160 31 Jcal unas cumes percepon. Sotanadlo Ear Rovns 6,p2= 172073
- SANTOS, LUIZ DIEGO VIDAL: HOLANDA, E 5, R; OLIVEIRA, CV 5; Post Aco MENEZES, V.B: VILLWOCK. XP. Purchase Intandon ot Amazon sstanabia erande a yr Sopra i euciualoquston modeling and Rash mode. SN Buss & Economies. vp 207, 202.
- SANOEIRA, ARLMARA ABADE; SANTOS, LUIZ DIEGO VIDAL; USIRAJARA. WILSONITA DE MELO; MACHADO, JOSE DOS SANTOS; BARRETO, IKARO DANIEL DE CARVALHO: HOLANDA FRANCISCO SANDRO RODRIGUES, RELAÇÃO ENTRE A PRODUÇÃO CIENTÍFICA E A PRODUÇÃO TECNOLÓGICA SOBRE ÀS INOVAÇÕES BASEADAS NÃ UTILIZAÇÃO DE BIOPOCIMEROS NA. CONSTRUÇÃO CIVI. RECINAZ - Rovsa Cientes Muleiseilnsr ISSN 2079-6218, vá, pins10408, EA COSTA A A HOLANDA. FS. R: SINA, F! SANTOS, 1 R;ARAUJO, 1: SOUZA AS. SANTOS, LD. V: PEDROTTI,A. Tre Lara Aoíudo AscasmentSyotom olhe Som: vi Area in Serge. Blat AMAZONIAN JOURNAL OF AGRICULTURAL ANO ENVIRONMENTAL SCIENCES /| REVISTADE CIÊNCIAS AGRÁRIAS. 6, 01, 2024 HOLANDA FS. R: SANTOS, L. D. Vi SANTOS-SOGRNHO, RA ;MENEZES, PV 9; SANTOS, 1 R. Aualação des carctrcicas técnicas ds cala vtvor a pacplum para Ui om tcncas da força dedo sob ameaça d eoeão,Posquea Agropocuai Tropical (Oni) e, BZ p.7 IGT
- SANTOS 04 HOLANDA, FRANCISCO SANDRO RODRIGUES: OLIVEIRA, CV 5. HOLANDA, VAR: CAMPOS. MS. MACHADO, . Brand oquysviantvolovartamento tório sobra meras feacionagas a exploração Horst CONGILIUM (BRASIL) 22, 1 - 15, 2027
- ESSON, GAgricL CARLOS MOURA: PISCOYA, VICTOR CASNURO; ROL NETO, FERNANDO CARTAXO: ARAÚJO FILHO, RENISSON NEPOMUCENO DE. MELO. ROBSON CARLOS PEREIRA DES PESSOA URIEL CALISTO NOURA! AVR, LUCAS JOSE DE SOUZA, CUNHA FILHO, MORAES, ALEX SOUZA; COMES FILHO, RAMIUNDO RODRIGUES; MEDEIROS, RAIMUNDO MAINAR. DES SABOVA,LUCUNO MARCELO FALE! Pedro, Alem: HOLANDA, FRANCISCO SANDRO. RODRIGUES, FERNANDES, MILTON MARQUES. SANTOS, LUIZ DIEGO VIDAL. Catton arc togem Soc anáhscicogica Actty Uns Forest Postura Sytem and Tiadinal Patu Permambuco. FLORAM. Em, 29, 620210068, 2022 EBBIVIDAL SANTOS, LUIZ DIEGO; CRUZ CM E: HOLANDA, FS R: SANTOS 1.1.0: 0185, CT. Carâmca atsanal da região do bao São range: potencia de indicação gaográtia ncia à fem o produção, CADERNOS UNIFOA ONLINE) 4.17. .2º- 28, 2022
- SSANDEIRA, ARLMARA ABADE: HOLANDA, FRANCISCO SANDRO RODRIGUES; Ancrado . E O; OURO FILHO, À M; MACHADO
- S: VIDAL SANTOS, LUIZ DIEGO. Charactenzaioncr no Iechnclogia cooper neburk à inovatine Based on e usa dr polar by he coil contuon indu cu social netwrk nai, INTERNATIONAL JOURNAL OF DEVELOPVENT RESERRCH vi poroGa, goza
- OLANDA, FRANCISCO SANDRO RODRIGUES: DANTAS, JOSÉ OLIVEIRA; SANTOS, ALA, TAINY BARRETO FRANCISCO DOS, ROCHA JUNIOR. VALTER FERREIRA: SANTOS, MARIA HOSANA. DOS SANTOS, LUIZ DIEGO VIDAL, Oinánica hatossedimanttigica do io Posm Aga à jusant da Bartegem Jam Umbelno em Sor, Bra JOURNAL OF ENVIRONMENTAL ANALYSIS AND
- PROGRESS, 7, pOr “082 2023 EEB asiNhO JUNIOR, JOSUÉ LUIZ; CASTRO, JAM BRITO DE; LINA, DAYANE DE SOUZA; SANTOS, LUIZ DIEGO VIDAL; PISCOVA, VICTOR CASIMIRO, CUNHAFILHO, MOACYR: FEITOSA, THAIANA BRUNES; ARAUJO FILHO, RENISON NEPONUCENO DE. Envronmenil indeatora for monitora col arte under ron vel covers ho caso of the scuhem cotado ot Tocantins RESEARGR SOCIETY ANO DEVELGPMENT vt passa tazrese, 252% HOLANDA, FRANCISCO SANDRO RODRIGUES; SANTOS, LUIZ DIEGO VIDAL: SANTOS | SOBRINHO, VALTER RUGENS ALCANTARA: MENEZES, PEDRO VINÍCIUS BERTULINO DE: SANTOS, TEFERSON RIBEIRO, Evaluation ra peter charco vetar and papa grassa for Uso in sol rvorcomar lecrrquos under crosin Et. Pesquisa Agropecuaria Tropical Ono) e, US per verNot7, 2022 EEE sOLANDA, FRANCISCO SANDRO RODRIGUES; SANTOS, LUIZ DIEGO VIDAL: Peer, ey: DE ARAÚJO FILHO, RENISSON NEPONUCENO; SARTOR, LUCAS RESMINE SANTOS: SOBRINHO, VALTER RUBENS ALCANTARA. DE JESUS, RAVSSA JULIANE SOUZA. De OLIVEIRA Silva, PRISCILA ANGEL: ANDRADE, KEILA MARIA ARAÚJO, Evalutan fine 10 seta of Veio grass Icreysopogem raid . Robe] using fre sampling mein Emaroomenal System Rescaen Mp6 31, 2022.
- RocóFIO ROCHA, BEXENBAUER: SANTOS, LUIZ DIEGO VIDAL; SIVA IARIANUNES DA; HOLANDA, FRANCISCO SANDRO RODRIGUES. Mat d atatógias de inovação para empresas da base ieorelóge. CONIECTURAS. v22 pisa - 56, 2022 A EA
- Machado, JOSÉ DOS SANTOS HOLANDA, FRANCISCO SANDRO RODRIGUES; SANTOS, NOGUEIRA, TONIGLAY ANDRADE. Prtoção da Propriadad Iroloctuar uma revisão ca cogurança dos dos digas e 40U8 desafio, CONJECTURAS. .22 76 - 2 2022
- FERREIRA, OLAVO JOSÉ MARQUES; HOLANDA, FRANCISCO SANDRO RODRIGUES; Pero Alceu: VIDAL SANTOS, LUIZ DIEGO, SLVAMANN, RENATA, Roo: System o Provido: Rostanco ana Suenginans o ro Sd. COMMUNICATIONS IN SOIL SCIENCE AND PLANT ANALYSIS, IR, 54 p= 13 2022
- BMOLANDA, FS. R SANTOS, MH; JESUS
- B: SANTOS, W M; SENA E 0.4; CHAGAS T. X-G0ES,1.H D.A: SANTOS, LUIZ DIEGO VIDAL Agora do sadiments do a rbora dl ro Sar Francos: eres de Brasi, en period de Boa descarga, Revit cd Investigaciones Gempáfcas 105, pastas, 2021 EBBactéio
- HOLANDA. E S R: SANTOS, LD. V: MENDONCA 8 5. JESUS,R 1.5.4 SILVA PA O, Avdiação da fiência da implantação de tácrca da bioanganhaia a sola, REVISTA BRASILEIRA DE GEOGRAFIA FÍSICA v.14 25-27, 2021
- MOLANDA FS. NANDERLEY LL; SANTOS, LD. Vi ROCHA, PSOLIVEIRA 1.5. Pesto Alau, BORT-CENERATED WAVES AND EROSION ON THE SHORE OF THE XINGÔ POWER PLANT RESERVOIR. GEOCIÊNCIAS (SÃO PAULO. ONLINE) v40,p 357 - 285 2021
- NUZ EL 2: AMEIDA 8.6: PISCONA VC ARANIO FLHO RN: CU FIO GUERRA S. MS) MELO RC. P, PISCOVA, TO, F. CASTRO 1.8. HOLANDA FS. R, PEDRO. AJ GOMES FILHO. RR. FERNANDES, MM, FEITOSA, TB; SANTOS, L. DV. RONCAL 1.1 P. Changes in inftradin under difere vegetais coverage in ota o e samiar Pemambucano Braz INTERNATIONAL JOURNAL OF DEVELOPMENT RESENRCH vp 48788 - 46789, 202% EBBPISCOYA V. CG: CRESPO,G. MG; ARAUJO FILHO, RN; POLICARPO, 3.5.4; CAVALCANT, BELL: SGUZA KA: MORAES, AS: CUNHA FILHO, tl: PESSBA Gr MÉLO, RE TAVARES, RG. FEITOSA 1.8; FERNANDES, MM; GOMES FUMO, RR. DIAS
- L A; SANTOS, LD. W, Conector Soa cksty inn Orgaie System o! Shadomod Cole. ANNUAL RESEARCH &. REVEWIN BIOLOGY 130, 1-6 2021 HOLANDA, FRANCISCO SANDRO RODRIGUES: DIAS K LL. D: SANTOS, LUIZ DIEGO VIDAL: BRITO CR M MELO, À CR SANTOS, LS, DEVELOPHENT AND MORPHONETRIC CAUÃ TERISHCS OE VETVER GRASS UNDER DIFFERENT DOSES O ORGANI FERTLIER Renta Castnga, JOR 345.20, 2021
- ROCHA. 12: HOLANDA, E SR ROLIM, MM; Podrt,Acsu: MOURA, MM; SANTOS, LUIZ DIEGO VIDAL. Diect Shea Srençih co he São Francisco River Bank Noieastem Braz, ih or Wihou Roca ol Diieron! Nabvo Species. JOURNAL OF AGRICULTURAL STUDIES, p.4-26, SANTOS, L.D. V: HOLANDA, E S.R;QUEROL, A P;VILNOCK A P 5. ENPREENDA AGROCAST PODCASTS PARA INPULSIONAR AS HABILIDADES EMPREENDEDORAS NAS CIÊNCIAS AGRARIAS HUMANIDADES & INOVAÇÃO, vê 3 2021
- VIDAL SANTOS, LUIZ DIEGO; HENEZES, PEDRO VINÍCIUS BERTULINO DE; HOLANDA, FRANCISCO SANDRO RODRIGUES; SOUSA. ALEXSANDRO DA FONSECA DE; ARAUIO FILHO, RENISSON NEPONUCENDO OE! OLIVEIRA, CRTUXE VARJRO DE SANTANA ENES, ADLSON MACHADO, VALE, WELINGTON GONZAGA DO, Empreendedor a grculura extensa náo da terra inamecinal. CONUECTURAS 21, 6.158 18, 2021
- FONTES C 5: HOLANDA FS R;ARAUJO FILHO, RN: VIDAL SANTOS, LUIZ DIEGO: NATURAL FBERS 4 THE MARGIN OE SÃO PRANCISCO RIVER, Carinho de Geografia) v.22,025
- 2021 SANTOS, LD HOLANDA, FS. R; SANTANA, MS, AZEVEDO, RC. Ferramenia esucacionainas Giências Apáris: o Programa Emproon Agro Suslntâvel como inter do comecrtamento preenádio REVISTA BE ESTUDOS E PESQUIBIO SOBRE ENSINO TECNOLÓGICO 7, perante soar
- Quintino, MS; HOLANDA, ES. R: MOURA ER; SANTANA 8; SANTOS, L.D.V; SINA, D.S, La reaciên err la infaesrctura de conocer Sento y al crecimento Insira! bras ANERICALATINA HOY. JOR vp 1-2 2021 SANTOS, LD. HOLANDA, FS. R. MENEZES, 2 VB; MARINO. RH FREITAS, 1: ANDRADE, CEL, NODELO MULTICRITÉRIO DE APOIO À DECISÃO SOBRE O USO DE FUNGOS
- MIGORRÍZICOS EM FABACEAS, Rovísa Ibero americana do Ciências Amsientas 12,91, 2021
- Sons, 5; HOLANDA, FS. R: SANTOS, LD, V; FELIZOLA HP M; FLORENCIO,M S. Panorama das startup no sto tuo braslio. PRISMA COM 4, 108 122,2021 HOLANDA, SR: SANTOS, LD.V; SANTANA, MS AZEVEDO, RG LEITE JUNIOR E 5: JESUS,R 1.5.1. Programa Empreanda AGRO Sustantávei amprandadormo a ovação no amiiente Resdbmico das GânczeAgrrie REVISTA BRASILEIRA DE ADMINISTRAÇÃO CENTÍPICA 112 pt
- HOLANDA, FRANCISCO SANDRO RODRIGUES; ARAUJO, RN.F: Poot, Aleu; WLGOX, 3. PEMARINO RH; SANTOS, L. D. V, Sol boengnering in orhessiam Brazi: An Ovni Revista Ambiente e Agua. 16, 82660, 2021
- SANTOS, L. D. V. HOLANDA, E 5 R: SANTANA, 4.5. JESUS.R. 1 5; Pod, aca ANDRADE, CARLOS EDUARDO CELESTINO DE. TantingEntegranauraio na Agrela Sclnces: Fr Practical Caso ot e Emproonda Rgro Sutenáva Program, JOURNAL OF STUDIES IN EDUCATION vip 12021
- ANORADE, CARLOS EDUARDO CELESTINO DE; HOLANDA, FRANCISCO SANDRO RODRIGUES, UBIRAJARA, WILSONITADE MELO BANDEIRA, ARIHMARAABADE: SANTOS, LUIZ DIEGO VIDAL. Uma anátso bibiomótica sobra componentos bemocânicos do tlânio Igados a lemos bela gênio apcados em ares bombas ado saude RESEARCH, SOCIETY AND DEVELOPMENT vp 0810912059, 202 EMA y DA SALVA QUINTINO, HELIANA; RODRIGUES HOLANDA, FRANCISCO SANDRO: RODRIGUES MOURA, FABIO, RICARDO DE SANTANA. JOSE: VIDAL, LUIZ DIEGO. Vc eficency inte polenta peoueton ct neu local under tica] ropey asso TECHNOLOGY IX SOCIETY der 66, 101607 2021. ações: WES OP SCENE" S|BESCIDLIS 7 SANTOS, LUIZ DIEGO VIDAL: HOLANDA, F.S.R. SANTANA G. O.V. BANDEIRA. A: ANDRADE, CEC JESUS R 1.8; Santos, 8 AplcaivoEmpeeenda Ato Sustentável feramenta condutora pata o comportando ampreendodor REVISTA ELETRÔNICA COMPETÊNCIAS DIGITAIS PARA AGRICULTURA PANILIAR (RECODAP) V, 12214, 2020
- SANTOS, LD.V, HOLANDA, F.S.R: LSUS,R 1.5, Apoio Faniar no aporte toanceto para novos negócios resulanies de profs educacionais, CADERNOS DE POS-GRADUAÇÃO, vt, p146
- MOLANDA, É 5. SANTOS, LD. V: SANTOS, LD: SAnTOS- SOBRINHO. RA: MENEZES, PB. SANTOS JR. CARACTERÍSTICAS BIOTÉCNICAS DO CAPIM.VETIVER E DO CAPIM PASPAL LM PARA USO E OBRAS DE CONTENÇÃO DE TALUDES. RCA REVISTA DE CIÊNCIAS AMBIENTAIS (UNILASALLE) 34, p 20-30, 2020. Glações: mi Dé sotnce = 3 | Seopus:
- SANTOS, LUIZ DIEGO VIDAL: SANTANA, C. O. V. HOLANDA, FS. R;ANORADE CE C. Santos, MS: UBIRAJARA. W.. Porcapção do turista dani a Pandoíi da COVID-18 sobr o star Fleo da Are utizando o too Eletron Data Serra (EDS) RESERRCA, SOCIETY AND DEVELOPMENT 10, povo 106262 2020.
- EMBSANTOS, LUIZ DIEGO VIDAL: BRANDÃO NL 5; SANTANA C. OW; HOLANDA F.S.R. Peso Alcau, POLITICAS PÚBLICAS DE APOIO À CT&i E DESAFIOS PARA A SUSTENTABILIDADE ANBIENTAL INTERNET LATENT CORPUS JOURNAL 110 p.20 29, 2020
- EBBANORADE, CARLOS EOUARDO CELESTINO DE; HOLANDA, FRANCISCO SANDRO RODRIGUES. UBIRAJARA, WILSONITA DE MELO: BANDEIRA, ARILHMARA ABADE: SANTOS, LUIZ DIEGO VIDAL, Uma anáiso bilomótica da trntura aplicada a transferência de tecncloa em cóldas acombusthel RESEARCH, SOCIETY AND DEVELOPMENT vô. pa22is1201021, 2020

## Artigos aceitos para publicação
- SANTOS, L.D. V: HOLANDA ES, R:SILVA E G;ARAUJO FILHO RN: SILVA 8.5, SUSSUCH É MM: ALMEIDA. WS; SANTOS
- MConsenvaon agrcuture improves sol realiencs by inogratro enjical, chemical, an ilegal patwaye. Global Change Biology. Je, 202
- MMEIDA R 0.5: PEREIRA LM: SOUSA L FG: LEITE O C:MELOR CP; FERNANDES, Me; MORÃES, À 5. SANTOS, LD. V: HOLANDA F.S.R./ PEDROTIL À; ARAULO FILHO, R Mp of land us change o nirogen oc in hum acins,AGROFORESTRY SYSTEMS. Ie
- SANTOS, L. D. GANA 5 6; LEITE FILHO, 6.0. FERREIRA, CM: FRANCA S RS: SANTOS, AM G AZEVEDO JUNIOR ISHIZAK MT; HOLANDA, SR Reguiatoy Governo 1 Pryeica Educar: Enfocemeni Pacto na ren Profesnal Regula Coon, JOURNAL OF REGULATORY ECONONICS. Je, 2025 CRESPO.C. MG; PISCOVA, VC; MELO R CB; PEREIRA LM; SANTOS, LD. W; HOLANDA, ÉS R: PEDROTTLA. SENA S.A B; CUNHA FILHO, M: ARAÚJO FILHO. RM Tepograohic Moduinon So Finctonal Iictrs in Sado Cof Aorferesty System A lvan and Near Bases Approse. Sente Report JR, 2026. P; SANTOS, LUIZ DIEGO VIDAL, HOLANDA
- PEDROTT, A: PEREIRA LM: FEITOSA 1
- ARAÚJO FILHO, RN Vegotation Components ds Natue-Hasod Solon o Foda Runa an Sat Lossina Brasilian Somar Ecnsetem Lang Dogradaten à Dovolopmens. ER, 2025

## Livros
- SANTOS, LD; SANTOS, LDU; SANTANA, C. O. v. EXERCÍCIO FÍSICO E QUALIDADE DE VIDA
- NATERCEIRA IDADE, o Tmbui Dado Ebook 2017, vt pás
- SANTOS, L. D. V: SANTOS. LD SANTANA, G. O.V. PRINCÍPIOS DE GARANTIA DE QUALIDADE DE SOFTMARE e 1 Timbu: Ga do Ebook 2017, 1 n4S

## Capítulos de livros
- ENES,A M; SANTOS, JR: SANTOS, MF M: SANTOS, MR: PEREIRA, D.A: SANTOS, LUIZ DIEGO VIDAL. VALE, W. 6; RODRIGUES, 5; GAZZOLA. ); ANDRADE. V 1.5. Dispostio por ra ana de bospecld laar in: Engenhari: a máquina que cont o it Volume 0, e Eblora Conneciment Li, 2023 v1.7. 6.12
- SANTOS, L. D.V.; SANTOS LOU HOLANDA. ES Re GAGLINROL PR: CARVALHO A ARAUJO, | SR. SANTANA € O. V. PASTAGENS: APLICATIVO MÓVEL PARA AUXÍLIO DA PRODUÇÃO DE FORRAGEIRAS EM SERGIPE In. Cêncis Agr: Campo Premissa em Pesquisa 6, Bo Porta GrosasPR. Ai, 010, 1, po 130 36 SANTOS, Ly Gevtos £ O vi SANTANA OO v; cncuaço, e. contmção Deum APLICATIVO MÓVEL PARA O AUXILIO NA PRODUÇÃO DE PEQUENOS PRODUTORES RURAIS:
- IMPACTOS DAS TECNOLOGIAS NAS ENGENHARIAS, 41 Ponta Grossa: Atena 2017 1,9. 6202.

## Anais de eventos (completo)
- SANTOS, LD. U: SANTOS, LD, ENES,A M: HOLANDA. F.S.R.: RODRIGUES, 5; GAGUAROL, PR. Mentorca: 8. 5. DETERMINAÇÃO DOS NIVEIS DE UMIDADE DO 800 POR MEIO DE. METODOS OTIGOS Ih: CongrocdoErasloro de Agrametsorloia, 2019 Caelão. Anais do Congresso Brasílio de Agrometoorologia 201
- SANTOS, L. D.V.: SANTOS LD HOLANDA. ES R Santos HS Andado EC. Samos AP MAPEAMENTO TECNOLÓGICO SOBRE PATENTES MEDIANTE REFLORESTAMENTO AMBIENTAL Vncont Nacirai de PropradadoInlacuo, 201, lnenêpoi-SC: ANAIS ENPI São Crtovão” SÉ Associação do Proprado inllocual, 2018, vv. p 380 - 657 3 EBBuna E ::saNTOS, LD. V: SANTOS LOM Santos M.5 HOLANDA. FS R PANORAMA DAPROPRIEDADE INTELECTUAL RELACIONADA À LOGÍSTICA REVERSA DE RESÍDUOS SÓLIDOS te VOU Inematona! Sympcam n Tecimologeal Ino 2048, São Citi. 10 Itemallnal Symposium on Tachmologica Innovation. São Corão: AP 2018, 10, 1073-1081 SANTOS, L. D. V: SANTOS, LOW HOLANDA FS. R CARVALHO AM; ROSA, A CA Santos MS, PANORAMA DAS PROPRIEDADES INDUSTRIAIS DIRECIONADAS ÃO DESENVOLVIMENTO AGRÍCOLA PAMILIARNO SRASIL ir: 108 teravonal Sypostumem Techrelegi Inovatom, 2019, fear 10 International Symposium em Technological Imovation Ars EL 2010, 10, 81 686 3 Gumino HM SANTOS LD. SANTOS LON. HOLANDA FR: FERREIRA MD 6: M DE CASO ny Enconto Nacional do Prepriodasa inlecul 2019, loranópolk SC. ANAIS V ENPI São Cristão: Associação de Prepidae Intelecal 2018, 5, 872 78” 6 EBEIUGIRAARA MM; ROSA A C.A; SANTOS, LDA; SANTOS LD. V:HOLANDA SR. POSSIBILIDADE DE LICENCIAMENTO COMPULSÓRIO DO METODO THERASUIT UM ENSAIO” TEGRICO hn: Th intermatial Symposium n Tchocloges! mova. 2018, Sto Cetvão. 10 International Symposium on Technological Innovation. São Cristão: AI 2019, 10,759 -767 SANTANA, 7.6: SILVA, RA. B; RODRIGUES, 5: SANTOS, L.D.V. SANTOS, L. D.; PANDORFL HM QUISELIN| O. TECNICA BIOSFECHLE LASER PARA AVALIAÇÃO DE DANOS MECÂNICOS EM MANGA TONY Io UI Congresso Braglero do Engenharia Agricola. CONHEA 2019, 2019 Campnas.SP. AVN Congresdo Brasileiro de Engenharia Agricola - CONBEA 2019, CAMPINAS: SEBER 2010 p.10-15
- SANTOS 1: SANTOS, L. D. : SANTOS LD. ENES,A M.; RODRIGUES, 5. slOSPECHLE LASER APLICADO NA IDENTIFICAÇÃO DE ATIVIDADE BIOLÓGICA EM SOLOS in. Congrsao Sigea Engunbari Agr 2877 Mago, XIM Congresso Brno do Engenharia Agricola SANTOS, L. D. V: SANTOS, LV: GAGLIAROL PR. SANTANA O. V.; ENES AM; RODRIGUES. 5. CITROS SERGIPE: APLICATIVO MÓVEL PARA AUXÍL DA PRODUÇÃO CITRÍCOLA EN SERGIBE In: CongassoIntemacoal doe Gáncias Agrarias COINTER. 2017 NATAL Congresso Internacional das Ciências Agrárias CONITER. Rocio. PE PDIAGRO, 2017 12
- SANTOS, LD. ; SANTOS, LOU ENES,A M; RODRIGUES
- SANTOS, A; SANTANA C.O. V. ESTUDO DA FREQUENCIA DE INTERAÇÃO DA ATIVIDADE B1OLOGICA EM SOLO DE TIPO ARGISSOLO VERMELHO AMARELO PELO MÉTODO DE BIOSPECIAE DINÂMICO i. Congresso, Intenso! des Clêncie Agrária COINTER, 2017, NATAL. U Congresso Intermacionl das Ciências Rorárias CONTER Rocio EE! POVAGRO, 2017 v'2

## Anais de eventos (resumo)
- E SANTOS 1.1 R ENES,A M VALE W.G: SANTOS, LUIZ DIEGO VIDAL; PEREIRA D.A. AP ENCONTRO DE INICIAÇÃO CIENTÍFICA EI | CIÊNCIAS AGRÁRIAS. 2020, São Cncôn, USE DE ALGORTOS DE PROCESSAMENTO DO BIOSPECHE PARA O RASPBERAY 138. ão CrSindo Rel Ierscplnar de Pesquisa é Inovação, 2020 7, p 86 86

## Anais de eventos (resumo expandido)
- ER ne E a 15 SILVA PA O: HOLANDA F.S.R; MENDONCA, 8. 5: JESUS, R 1 5:LMA LO 4: SANTOS, L. DV SANTOS LO METODOLOGIAS PARA AVALIAÇÃO DO SISTEMA RADICULAR DOS CAPS VETIVER E PASPALUNM USADOS NA RECUPERAÇÃO DE ÁREAS EM PROCESSOS EROSIVOS ly VI CONGRESSO NORDESTINO DE ENGENHARIA FLORESTAL I WORKSHOP DO PROJETO GANTNOA
- Ny Engenharia lotestal no Nordst: Montado Desenvolvimento” fosse: Cala Jon da Sh era 2018, 2.05 "618 SANTOS, L.D. V: SANTOS LD, SANTOS, 1 A; ENES,A M; RODRIGUES
- AJUSTE DE ALGORTIOS PARAANÁLISE BA CORRELAÇÃO ENTRE VALORES DE MI E UIMBADE DO SOLO In 27º ENCONTRO DE INICIAÇÃO CIENTÍFICA EI 2018 ão Cristão. Revista Imeriseiplnar de quis Inovação, São Crsarão Re. 2016 vá, pl2-02 SANTOS, 1 4; SANTOS, LD. V; SANTOS, LOM; ENES,A M; RODRIGUES, 5, corcTADE DADOS E PREPARAÇÃO DE AMOSTRAS DE SOLO PARA ANALISE POR BIOSPEGKLE LASER In: 27º ENCONTRO De INICIAÇÃO CIENTIFICA IC, 2078, São Crstinão. Livro de rotumos do 26º Encontro de Inilação Científica. São Chstvão Ro. 2018, vá, p= 2 SANTOS, LD. SANTOS LO SANTOS, 1 A;ENES A M; RODRIGUES, ESTUDO A FREQUÊNCIA DE INTERAÇÃO DA ÁGUA EM SOLO DE TEXTURA ARENOSA APLICANDO WAVELETS fr: Congraão raslaro da Engermaria Agrcl, 2017. Meca. XLVI Congresso Brasileiro de Engenharia Agricola: CONBER 2017. São Baú: SEA 2017, SANTOS, LD. V; SANTOS, LOM ENES, AM; SANTOS, JA, BIOSPECKLE LASER APLICADO NA IDENTIEICAÇÃO DE ATIVIDADE BIOLOGICAEM SOLOS hn 26 Encoiro dl Iniciação Cintia da UFS 2016 Sho Cosióio, Livro de Resumos 2ão Encontro de inicição clentílicada UPS. São Cretino UPS, 2016 vã, ps 66 SANTOS, LD. V: SANTOS, LOM; SANTOS, J A: ENES,A ML ESTUDO DAFREQUENCIADE INTERAÇÃO DA AGUA EM SOLO DE TEXTURA ARENOSA In 26º Encontro de siclação cedia da
- UFS, 2076, São Cretôvaão. Livro de Resumos 260 Encontro do iniciação clentíca da UFS. São Citinaão UPS, 2010, 126, 40-40 MENDONCA, 11; SANTOS, L.O.V, CARVALHO, TA. OLIVEIRA PR; MARINO, RH ASSOCIAÇÃO MICORRIZICA DE FMAS CON G TOMATEIRO 906, EM CULTIVO ORGÂNICO In 254 encon o. iniciação dentes. BI, 2016, São Criavão, Livro de resumos 25º encontro de iniciação cientifica das 2015 MENDONCA, 1.1: OLIVEIRA, P R.: MARINO, RH: CARVALHO, TA: SANTOS, L.D.V: SANTOS, ML AVALIAÇÃO DA SIMBIOSE ENTRE TOMATE IPAOS E FUNGOS MICORRÍZICOS ARBUSCULARES. EN SUBSTRATO ORGÂNICO In: 006 Congrasco Nacinal e Glncias do Seo 2015, Netal. O Solo e Suas Mutiplas Funções. 2013 p2.5 SANTOS, LD. OLIVEIRA PR. CARVALHO, TA MENDONCA, 1. 3; MARINO, RH EFEITO DE INOCULARTES ICORRÍCOS NO DESENVOLVIMENTO E NA PRODUÇÃO DE TOMATE TIO CEREJA COMUM In: 25 enconto do intiação cena EI, 2018, Sã Cristóvão, Livro de resumos 25º encontro de Inleiação cientifica da UFS. 2015. CARVALHO, TA SANTOS, L.D.: MENDONCA 1.1: SANTOS, GM; MARINO, RM EFEITO DO INOCULANTE MICORRÍZICO ARBÚSCULAR NO DESENVOLVIMENTO E NA PROOUÇÃO DO TOMATE TIPO CEREJA PENDENTE (TOMATE UVA) 25 encontro do nação cinta EIC, 2015, São Crativão. Livro de resumos 25 encontro de iniiaçãoclentfica da UFS, 2015, SANTOS, LD. MARINO, RM; CARVALHO, TA: OLIVEIRA, PR. MENDONCA, 1.4. FUNGOS MIGORRIZICOS ARGUSCULARES E TOMATE CEREJA: ESTUDO DA COLONIZAÇÃO MICORRÍZICA NO CRESCIMENTO VEGETATIVO In: 006 Congresso Braslero de Ciâncis do Sao 2018, Natal O Solo suas múltiplas Funções. 2015, p.01 5 SANTOS, LD. MARINO, RM: OLIVEIRA, PR CARVALHO, TA MENDONCA, 1.1 FUNGOS MUCORRIZICOS ARBUSCULARES NO CRESCIMENTO VEGE TÁTIVO E REPRODUTIVO DO TOUATE TEREI 3000 Congreso Nacional do Gênese do Solo, 2018, Netal. O Solo o suas mútipias tunções. 2018, MENDONCA, 4 4: OLIVEIRA, PR. MARINO, RM: CARVALHO, TA: SANTOS, L DIV; SANTOS, O. ML TOMATE 208. DESENVOLVIMENTO VEGETATIVO E REPRODUTIVO COM FUNGOS. MUBORRIZIGOS ARBUSCULARES iz 200 Coitado acionado Clênias do Sol
- Nata Selos o suas Múltiplas funções 2015, ÊY SANTOS, L.D.V; MARINO. RH . CRESCIMENTO DE MUDAS DE TOMATE CEREJA REDONDO, EM BANDEIR COM FUNGOS NICORRIZICOS ARBUSCUL ARES In 24º ENCONTRO DE INICIA
- CENTIACADAUES, 2074 SÃO CRISTÓVÃO: LIVRO DE RESUMOS 24 ENCONTRO DE INICIAÇÃO CIENTIFICA DA UFS. SÃO CRISTÓVÃO UPS, 2014, p.15- 15 CARVALHO, TA. MARINO, RH; MENDONCA. 1 J: SANTOS, L.D.V. DESENVOLVIVENTO DE MUDAS DE TOMATE UVA MICORRIZADAS ln Reunião Norsina de Ciências do Soo
- Inéus. Agenda de Uso e conservação dos Solos: Por que nã? Ihéus. Sociedade Brsiira o Clos do Solo, 2014 pia 086

<!-- lattes:auto:end -->


<!-- references -->

# 2024

- **von Csefalvay C** (2024). DAEDRA: A language model for predicting outcomes in passive pharmacovigilance reporting. _arXiv_ [2402.10951](https://arxiv.org/abs/2402.10951).

# 2023

- Mogere E, Mwaura E, Waithaka M, Mutua V, Mugao M, **von Csefalvay C**, Mukamati D (2023). Juvenile polyposis syndrome: A case report. _Clinical Case Reports_ 2023;**11**:e6798. doi:[10.1002/ccr3.6798](https://doi.org/10.1002/ccr3.6798)

# 2022

- Mutua V, Henry B, **von Csefalvay C**, Cheruiyot I, Vikse J, Lippi G, Bundi B, Mong’are N (2022). Tocilizumab in addition to standard of care in the management of COVID-19: A meta-analysis of RCTs. _Acta Bio Medica: Atenei Parmensis_ 2022;**93**. doi:[10.23750/abm.v93i1.12208](https://doi.org/10.23750/abm.v93i1.12208)

- Bundi B, Mutua V, Cheruiyot I, Munguti J, **von Csefalvay C**, Nurani K, Ogeng’o J (2022). The Unusual High Origin Radial Artery in a Black Kenyan Population: A Cadaveric Study. _Ethiopian Journal of Health Sciences_ 2022;**32**. doi:[10.4314/ejhs.v32i2.25](https://doi.org/10.4314/ejhs.v32i2.25)

- Munguti J, Mutua V, Cheruiyot I, **von Csefalvay C**, Opare-Addo P, Kiko N, Wanjiru R (2022). Tuberculous polyserositis in endemic areas with an emphasis on empiric therapy: A case report. _Medicine: Case Reports and Study Protocols_ 2022;**3**:e0221. doi:[10.1097/MD9.0000000000000221](https://doi.org/10.1097/MD9.0000000000000221)

# 2021

- **von Csefalvay C** (2021). VAERS data reveals no increased risk of neuroautoimmune adverse events from COVID-19 vaccines. _medRxiv_. doi:[10.1101/2021.06.13.21258851](https://doi.org/10.1101/2021.06.13.21258851).

- **von Csefalvay C** (2021). Early evidence for the safety of certain COVID-19 vaccines using empirical Bayesian modeling from VAERS. _medRxiv_. doi:[10.1101/2021.06.10.21258589](https://doi.org/10.1101/2021.06.10.21258589).

- **von Csefalvay C** (2021). A case-control study of autoimmune AEFIs following COVID-19 vaccination reported to VAERS. _medRxiv_. doi:[10.1101/2021.07.06.21260074](https://doi.org/10.1101/2021.07.06.21260074).

- **von Csefalvay C** (2021). Anaphylactic events in mRNA vaccines: a reporting case-control study. _medRxiv_. doi:[10.1101/2021.07.19.21260714](https://doi.org/10.1101/2021.07.19.21260714).

- Mutua V, Mong’are N, Bundi B, **von Csefalvay C**, Oriko D, Kitunguu P (2021). Sudden bilateral lower limb paralysis with dural ectasia in Neurofibromatosis type 1: A case report. _Medicine: Case Reports and Study Protocols_ 2021;**2**:e0165. doi:[10.1097/MD9.0000000000000165](https://doi.org/10.1097/MD9.0000000000000165)

- Mpekethu N, Mongare N, Mutua V, Wangari M, **von Csefalvay C**, Ojuka D (2021). Knowledge and attitudes of undergraduate medical students in Kenya towards solid organ donation and transplantation: Are Africa’s future clinicians prepared?. _African Journal of Nephrology_ 2021;**24**:89--94. doi:[10.21804/24-1-4843](https://doi.org/10.21804/24-1-4843)

# 2020

- **von Csefalvay C**, Foldi T (2020). PAWS: Towards a globally integrated outbreak surveillance system for public health. _Zenodo_ 2020. doi:[10.5281/zenodo.3782871](https://doi.org/10.5281/zenodo.3782871)

- Foldi T, **von Csefalvay C**, Perez N (2020). Jampi: Efficient matrix multiplication in Spark using barrier execution mode. _Big Data and Cognitive Computing_ 2020;**4**:32. doi:[10.3390/bdcc4040032](https://doi.org/10.3390/bdcc4040032)

- **von Csefalvay C** (2020). Statistical dynamics of social distancing in SARS-CoV-2 as a differential game. _arXiv_ [2007.13734](https://arxiv.org/abs/2007.13734).

- **von Csefalvay C** (2020). Vector quantisation and partitioning of COVID-19 temporal dynamics in the United States. _arXiv_ [2008.00559](https://arxiv.org/abs/2008.00559).

# 2019

- **von Csefalvay C** (2019). Novel quantitative indicators of digital ophthalmoscopy image quality. _arXiv_ [1903.02695](https://arxiv.org/abs/1903.02695).

# 2015

- **von Csefalvay C** (2015). Ecological metrics of diversity in understanding social media. _arXiv_ [1501.07621](https://arxiv.org/abs/1501.07621).

# 2009

- **von Csefalvay C** (2009). On Good Intentions and Poor Outcomes: A Critical Retrospective on Chester v Afshar. _UC Dublin L. Rev._ 2009;**9**:46.

# 2007

- **von Csefalvay C** (2007). Taunts, Chapati Pans and the Case of the Reasonable Glue-Sniffer: An Examination of the Normative Test in Provocation after Smith and Holley. _Cambridge Student Law_ 2007:45--52. doi:[10.2139/ssrn.1334048](https://doi.org/10.2139/ssrn.1334048)


