---
title: "Estatística Descritiva"
subtitle: "Medidas de Tendência Central e Dispersão<br>Análise de Dados Ambientais"
author: "Luiz Diego Vidal Santos"
institute: "Universidade Estadual de Feira de Santana (UEFS)"
format:
  revealjs:
    logo: ../../../assets/logo-uefs.webp
    footer: "UEFS | Análise de Dados Ambientais | Estatística Descritiva"
    slide-number: true
    theme: [simple, ../../../assets/uefs.scss]
    controls: true
    width: 1280
    height: 720
    css: ../../../assets/custom.css
    transition: slide
    background-transition: fade
    preview-links: auto
execute:
  echo: false
---

# [ESTATÍSTICA DESCRITIVA]{.section-header}

## ESTATÍSTICA DESCRITIVA {.smaller-text}

Diego Vidal


---

## ESTATÍSTICAS DESCRITIVAS {.smaller-text}

O que aprenderemos:

Medidas de tendência central

  - Média simples
  - Moda
  - Mediana
Medidas de dispersão

  - Variância
  - Desvio-padrão
  - Erro-padrão
  - Intervalo de Confiança
Escore Z


---

## ESTATÍSTICAS DESCRITIVAS (cont.) {.smaller-text}

O que são

- A estatística descritiva é um ramo da estatística que aplica várias técnicas para descrever e sumarizar um conjunto de dados.
- Diferencia-se da estatística inferencial, que tem por objetivo obter
uma afirmação acerca de uma população com base numa amostra.


---

## TENDÊNCIA CENTRAL {.smaller-text}

**Objetivos**: Encontrar um valor que resuma a variabilidade de um conjunto de dados.

**Pesquisa**: Investigar os níveis de crescimento radicular frente ao uso de fungos micorrízicos  arbusculares (N = 17).

Instrumento de 34 itens

Comprimento (cm)

Escores variam de 34 cm a 170 cm


---

## TENDÊNCIA CENTRAL (cont.) {.smaller-text}

**MÉDIA**

**Pesquisa**: Investigar os níveis de atitude frente ao uso de drogas ilícitas (N = 17).

Escores variando de 34 a 170

2148

17

Média = 126,35

=

*N*


| Escores dos repetições |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 94 | 104 | 107 | 109 | 113 | 117 | 117 | 121 | 127 | 128 | 130 | 132 | 137 | 143 | 153 | 154 | 162 |


---

## TENDÊNCIA CENTRAL (cont.) {.smaller-text}

**MODA**

**Pesquisa**: Investigar os níveis de crescimento radicular frente ao uso de fungos micorrízicos  arbusculares (N = 17).

Escores variando de 34 a 170

**MODA**: O número que aparece mais vezes

117 = 2 vezes; (Unimodal)


| Escores dos repetições |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 94 | 104 | 107 | 109 | 113 | 117 | 117 | 121 | 127 | 128 | 130 | 132 | 137 | 143 | 153 | 154 | 162 |


---

## TENDÊNCIA CENTRAL (cont.) {.smaller-text}

**MEDIANA**

**Pesquisa**: Investigar os níveis de crescimento radicular frente ao uso de fungos micorrízicos  arbusculares (N = 17).

Escores variando de 34 a 170

**MEDIANA:**** **O número que divide a amostra em duas metades iguais


| Escores dos repetições |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 94 | 104 | 107 | 109 | 113 | 117 | 117 | 121 | 127 | 128 | 130 | 132 | 137 | 143 | 153 | 154 | 162 |


---

## TENDÊNCIA CENTRAL (cont.) {.smaller-text}

**SUMÁRIO**

**Pesquisa**: Investigar os níveis de crescimento radicular frente ao uso de fungos micorrízicos  arbusculares (N = 17).

Escores variando de 34 a 170

**MÉDIA:**** **126,35; **MODA:**** **117; **MEDIANA:**** **127


| Escores dos repetições |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 94 | 104 | 107 | 109 | 113 | 117 | 117 | 121 | 127 | 128 | 130 | 132 | 137 | 143 | 153 | 154 | 162 |


---

## MEDIDAS DE DISPERSÃO {.smaller-text}

**Objetivos**:

Ter noção da variabilidade dos escores em torno da média;

Auxilia na interpretação sobre o quanto os casos são semelhantes ou diferentes entre si, frente à variável de interesse


---

## MEDIDAS DE DISPERSÃO (cont.) {.smaller-text}

**VARIÂNCIA**

**Pesquisa**: Investigar os níveis de crescimento radicular frente ao uso de fungos micorrízicos  arbusculares (N = 17).

Escores variando de 94 a 162

2

(*x**	*- *x*)2  (*x**	*- *x*)2  ...  (*x**	*- *x*)2

*n** *-1

*Variância**	*	*s**	* 	1	2	*n**	*


| Escores dos repetições |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 94 | 104 | 107 | 109 | 113 | 117 | 117 | 121 | 127 | 128 | 130 | 132 | 137 | 143 | 153 | 154 | 162 |


---

## MEDIDAS DE DISPERSÃO (cont.) {.smaller-text}

**VARIÂNCIA**

**Pesquisa**: Investigar os níveis de crescimento radicular frente ao uso de fungos micorrízicos  arbusculares (N = 17).

Escores variando de 94 a 162

2

(*x** *- *x*)2  (*x** *- *x*)2  ...  (*x** *- *x*)2

*n** *-1

*Variância**	* *s**	* 	1	2	*n**	*

MEDIDAS DE DISPERSÃO


| Escores das repetições |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 94 | 104 | 107 | 109 | 113 | 117 | 117 | 121 | 127 | 128 | 130 | 132 | 137 | 143 | 153 | 154 | 162 |
| Média = 126,35 |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |


---

## MEDIDAS DE DISPERSÃO (cont.) {.smaller-text}

**VARIÂNCIA**

**Pesquisa**: Investigar os níveis de crescimento radicular frente ao uso de fungos micorrízicos  arbusculares (N = 17).

Escores variando de 94 a 162

2

(*x** *- *x*)2  (*x** *- *x*)2  ...  (*x** *- *x*)2

*n** *-1

*Variância** * *s** *   1	2	*n**	*


| Escores das repetições |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 94 | 104 | 107 | 109 | 113 | 117 | 117 | 121 | 127 | 128 | 130 | 132 | 137 | 143 | 153 | 154 | 162 |
| Média = 126,35 |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| -32,35 | -22,35 | -19,35 | -17,35 | -13,35 | -9,35 | -9,35 | -5,35 | 0,65 | 1,65 | 3,65 | 5,65 | 10,65 | 16,65 | 26,65 | 27,65 | 35,65 |


---

## MEDIDAS DE DISPERSÃO (cont.) {.smaller-text}

**VARIÂNCIA**

16

= 361,74

=

5787,9

*n-**1*

(xi – *-*x)2

*S**2** **=*

MEDIDAS DE DISPERSÃO


| Diferença das médias |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| -32,35 | -22,35 | -19,35 | -17,35 | -13,35 | -9,35 | -9,35 | -5,35 | 0,65 | 1,65 | 3,65 | 5,65 | 10,65 | 16,65 | 26,65 | 27,65 | 35,65 |
| 1046,5 | 499,5 | 374,4 | 301,0 | 178,2 | 87,4 | 87,4 | 28,6 | 0,4 | 2,7 | 13,3 | 31,9 | 113,4 | 277,2 | 710,2 | 764,5 | 1270,9 |


---

## MEDIDAS DE DISPERSÃO (cont.) {.smaller-text}

**VARIÂNCIA**

**DESVIO-PADRÃO**

16

= 361,74

=

5787,9

*n-**1*

(xi – *-*x)

*S**2** **=*

*DP** **=**	*19,02


---

## MEDIDAS DE DISPERSÃO (cont.) {.smaller-text}

*EP **=** *	DP   		*=** * 19,02 *=**	*4,613

𝑁	17

**ERRO-****PADRÃO**

**Desvios-****padrão**** ****entre**** ****as**** ****médias das**** ****amostras (Field,**** ****2005)**

MEDIDAS DE DISPERSÃO


---

## MEDIDAS DE DISPERSÃO (cont.) {.smaller-text}

**Pesquisa**: Investigar os níveis de crescimento radicular frente ao uso de fungos micorrízicos  arbusculares (N = 17).

Escores variando de 34 a 170.

M = 126,35; DP = 19,02; EP = 4,61

MEDIDAS DE DISPERSÃO


---

## {.smaller-text}

ESCORE Z


---

## ESCORE Z {.smaller-text}

Z = X – X

*s*

Onde:

O escore z é uma transformação dos escores brutos, baseadas em desvio- padrão, cuja fórmula é:

*_*

X = escore da amostra;

*_*

X = média amostral;

S = desvio-padrão amostral


---

## ESCORE Z (cont.) {.smaller-text}

Imagine uma variável cuja média é 20 e o desvio-padrão é 2

Se uma repetição tem escore 22, ela está um DP acima da média, logo seu escore Z = 1;

*Z** *= X – X  = 22 – 20 = 1

*_*

*s**	**2*


---

## ESCORE Z (cont.) {.smaller-text}

**Logo:**

1 ponto no escore Z é igual ao valor do DP;

Vamos ao exemplo da M = 20; DP = 2.

  - Uma repetição que tem escore 18, está 1 DP abaixo da Média, logo o escore Z dela é -1.
  - Uma repetição com escore 28, está 4 DP acima da média, logo Escore Z dela é 4.

---

## ESCORE Z (cont.) {.smaller-text}

**O**** ****escore**** ****Z**** ****é**** ****útil**** ****para**** ****estimar**** ****o**** ****quão**** ****longe**** ****um**** ****sujeito**** ****está**** ****da**** ****média.**

Se a distribuição é normal, do total da amostra:

68,2% terão escore Z entre +-1;

95,4% terão escore Z entre +-2;

99.7% terão escores Z entre +- 3.


---

## ESCORE Z (cont.) {.smaller-text}

**O**** ****escore**** ****Z**** ****é**** ****útil**** ****para**** ****estimar**** ****o**** ****quão**** ****longe**** ****um**** ****sujeito**** ****está**** ****da**** ****média.**

Quando a amostra não é normal, essa estimativa de % não é precisa, de modo que o escore Z perde um pouco a sua utilidade.


---

## {.smaller-text}

INTERVALO DE CONFIANÇA


---

## INTERVALO DE CONFIANÇA {.smaller-text}

É uma outra forma de determinar a precisão da média amostral, como estimativa da média populacional.

Ao calcular o intervalo de confiança, você tem uma amplitude, onde se estipula que a verdadeira média da população estará.


---

## INTERVALO DE CONFIANÇA (cont.) {.smaller-text}

**INTERVALO**** ****DE**** ****CONFIANÇA**

Pode ser calculado em diferentes probabilidades (usando escore *z*): 90%, 95%, 99%

IC: M + Z*EP

90% = M + (**1,645**** **X EP)

95% = M + (**1,96**** **X EP)

99% = M + (**2,575**** **X EP)

Tabela Z-two-tails


---

## . {.smaller-text}

**INTERVALO**** ****DE**** ****CONFIANÇA**

Pode ser calculado em diferentes probabilidades (usando escore *z*): 90%, 95%, 99%

90% = M + (**1,645**** **X EP)

- Limite inferior: 126,35 – (1,645 X 4,61) = 118,76
- Limite superior: 126,35 + (1,645 X 4,61) = 133,92
95% = M + (**1,96**** **X EP)

- Limite inferior: 126,35 – (1,96 X 4,61) = 117,30
- Limite superior: 126,35 + (1,96 X 4,61) = 137,37
99% = M + (**2,575**** **X EP)

- Limite inferior: 126,35 – (2,575 X 4,61) = 114,46
- Limite superior: 126,35 + (2,575 X 4,61) = 138,21
.

.

126,34

*Limite **Inferior*

*Lower** **Bound*

*Limite superior*

*Upper** **Bound*

90%

95%

99%

INTERVALO DE CONFIANÇA


---

## INTERVALO DE CONFIANÇA {.smaller-text}

**INTERVALO**** ****DE**** ****CONFIANÇA**

90% = M + (**1,645**** **X EP)

- Limite inferior: 126,34 – (1,645 X 4,61) = 118,76
- Limite superior: 126,34 + (1,645 X 4,61) = 133,92
Média e EP fora da média populacional

Site didático sobre Intervalo de Confiança: https://rpsychologist.com/d3/ci/


# {background-color="#034EA2"}

[Obrigado!]{.obrigado-fit-text style="color: white;"}

::: {style="text-align: center; color: white; font-size: 0.7em;"}
Luiz Diego Vidal Santos

Universidade Estadual de Feira de Santana (UEFS)
:::

