graph LR
    D[1. DIAGNÓSTICO<br/>Mapeamento ativos] --> F[2. FORMULAÇÃO<br/>Estratégia PI]
    F --> I[3. IMPLEMENTAÇÃO<br/>Práticas concretas]
    I --> M[4. MONITORAMENTO<br/>Indicadores]
    M --> D
    
    D --> D1[Auditoria PI<br/>Matriz VRIO<br/>Competências essenciais]
    F --> F1[Mix apropriabilidade<br/>Portfolio integrado<br/>Branding estratégico]
    I --> I1[Rotinas confidencialidade<br/>Parcerias NITs<br/>Contratos trabalho]
    M --> M1[BSC inovação<br/>Vigilância tecnológica<br/>Métricas ROI-PI]
    
    style D fill:#003366,color:#fff
    style F fill:#0066CC,color:#fff
    style I fill:#00A859,color:#fff
    style M fill:#FF8C00,color:#fff